# Generated by Django 5.2.7 on 2025-10-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('window_type', models.CharField(choices=[('residential', 'Оконная рама (жилое помещение)'), ('commercial', 'Витрина (коммерческое помещение)'), ('car', 'Автомобильное стекло'), ('stained', 'Витражное стекло'), ('other', 'Другое')], max_length=20)),
                ('preferred_time', models.CharField(blank=True, choices=[('morning', 'Утром (9:00-12:00)'), ('afternoon', 'Днем (12:00-17:00)'), ('evening', 'Вечером (17:00-20:00)'), ('weekend', 'Выходные')], max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
