# Generated by Django 5.2.7 on 2025-10-21 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('morning', 'Утром (9:00-12:00)'), ('afternoon', 'Днем (12:00-17:00)'), ('evening', 'Вечером (17:00-20:00)'), ('weekend', 'Выходные')], max_length=20, null=True, verbose_name='Назначенное время'),
        ),
        migrations.AlterField(
            model_name='order',
            name='window_type',
            field=models.CharField(choices=[('residential', 'Оконная рама (жилое помещение)'), ('commercial', 'Витрина (коммерческое помещение)'), ('car', 'Автомобильное стекло'), ('stained', 'Витражное стекло'), ('other', 'Другое')], max_length=20, verbose_name='Вид работ'),
        ),
    ]
